[package]
name = "anchor-client"
version.workspace = true
rust-version.workspace = true
authors = ["Serum Foundation <foundation@projectserum.com>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/coral-xyz/anchor"
description = "Rust client for Anchor programs"
publish = ["star-atlas"]

[features]
debug = []

[dependencies]
anchor-lang.workspace = true
anyhow.workspace = true
regex.workspace = true
serde.workspace = true
solana-account-decoder.workspace = true
solana-client.workspace = true
solana-sdk.workspace = true
thiserror.workspace = true
url.workspace = true
