[package]
name = "anchor-cli"
version.workspace = true
authors = ["armaniferrante <armaniferrante@gmail.com>"]
edition = "2021"
repository = "https://github.com/coral-xyz/anchor"
description = "Anchor CLI"
license = "Apache-2.0"
publish = ["star-atlas"]

[[bin]]
name = "anchor"
path = "src/bin/main.rs"

[features]
dev = []
default = []

[dependencies]
anchor-client.workspace = true
anchor-lang.workspace = true
anchor-syn = { workspace = true, features = ["idl", "init-if-needed"] }
anyhow.workspace = true
cargo_toml.workspace = true
chrono.workspace = true
clap.workspace = true
dirs.workspace = true
flate2.workspace = true
heck.workspace = true
pathdiff.workspace = true
portpicker.workspace = true
rand.workspace = true
reqwest.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
shellexpand.workspace = true
solana-cli-config.workspace = true
solana-client.workspace = true
solana-faucet.workspace = true
solana-program.workspace = true
solana-sdk.workspace = true
syn.workspace = true
tar.workspace = true
tokio.workspace = true
toml.workspace = true
walkdir.workspace = true

# Locked versions
litemap.workspace = true
zerofrom.workspace = true

