[package]
name = "anchor-spl"
version.workspace = true
authors = ["Serum Foundation <foundation@projectserum.com>"]
edition = "2021"
license = "Apache-2.0"
description = "CPI clients for SPL programs"
publish = ["star-atlas"]

[features]
default = ["mint", "token", "associated_token"]
mint = []
token = ["spl-token"]
associated_token = ["spl-associated-token-account"]
governance = []
shmem = []
devnet = []
metadata = ["mpl-token-metadata"]
dex = ["serum_dex"]

[dependencies]
anchor-lang = { workspace = true, features = ["derive"] }
mpl-token-metadata = { workspace = true, optional = true }
serum_dex = { workspace = true, optional = true }
solana-program.workspace = true
spl-associated-token-account = { workspace = true, optional = true }
spl-token = { workspace = true, optional = true }
borsh.workspace = true
